In [2]:
import pandas as pd

## Basic info

Read the data-file (a 10 000 row subset of most rated IMDB-movies) into Pandas DataFrame and name the DataFrame-variable to `df` (use tab-character (`\t`) as the separator)

1. Use the following column-names: `ID, title, year, rating, votes, duration, genres`
2. Index the `df` with `ID`-column (either on reading the file or after it.)
3. Display first 5 rows of the `df`
4. Display last 11 rows of the `df`
5. Display the `df`-info

In [24]:
df = pd.read_csv('movie_data.txt',sep = '\t', names = ['ID','title', 'year', 'rating', 'votes', 'duration','genres'])

In [25]:
df.set_index('ID',drop=True,inplace = True)

In [26]:
df.head(5)

,title,year,rating,votes,duration,genres
ID,,,,,,
tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,142 mins.,Crime|Drama
tt0110912,Pulp Fiction (1994),1994,9.0,490065,154 mins.,Crime|Thriller
tt0137523,Fight Club (1999),1999,8.8,458173,139 mins.,Drama|Mystery|Thriller
tt0133093,The Matrix (1999),1999,8.7,448114,136 mins.,Action|Adventure|Sci-Fi
tt1375666,Inception (2010),2010,8.9,385149,148 mins.,Action|Adventure|Sci-Fi|Thriller

In [27]:
df.tail(11)

,title,year,rating,votes,duration,genres
ID,,,,,,
tt0101356,Another You (1991),1991,4.9,1359,98 mins.,Comedy|Crime
tt0421090,Zerophilia (2005),2005,6.3,1359,90 mins.,Comedy|Romance
tt0067227,The Merchant of Four Seasons (1971),1971,7.6,1359,88 mins.,Drama
tt0339727,Stateside (2004),2004,5.8,1358,97 mins.,Drama|Music|Romance
tt0218581,Scarlet Diva (2000),2000,5.2,1358,91 mins.,Drama
tt0118635,Aprile (1998),1998,6.7,1358,78 mins.,Comedy
tt0807721,Meduzot (2007),2007,7.0,1357,78 mins.,Drama
tt0339642,Daltry Calhoun (2005),2005,5.2,1357,100 mins.,Comedy|Drama|Music|Romance
tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller
tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance
tt0279977,The Navigators (2001),2001,6.9,1356,96 mins.,Comedy|Drama

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, tt0111161 to tt0279977
Data columns (total 6 columns):
title       10000 non-null object
year        10000 non-null int64
rating      10000 non-null float64
votes       10000 non-null int64
duration    10000 non-null object
genres      9999 non-null object
dtypes: float64(1), int64(2), object(3)
memory usage: 546.9+ KB